version: "3.7"
services:

  service:
    build:
      context: .
      dockerfile: Dockerfile-service
    networks:
      demo_net:
        ipv4_address: 172.28.1.5
    environment:
      - DB=${DB}
      - HOST=${HOST}
      - PASS=${PASS}
      - USER=${USER}
      - REDIS_MASTER_HOST=${REDIS_MASTER_HOST}
      - REDIS_READER_HOST=${REDIS_READER_HOST}
      - REDIS_MASTER_PORT=${REDIS_MASTER_PORT}
      - REDIS_READER_PORT=${REDIS_READER_PORT}
      - SQL_QUERY_TEXT=${SQL_QUERY_TEXT}
      - FLASK_ENV=${FLASK_ENV}
      - PYTHONPATH=${PYTHONPATH}
    expose: 
      - 80
    ports:
      - 80:80

networks:
  demo_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16